
project_id = "jwbcrddblmiurmeziszp"

[functions.cost-simulator]
verify_jwt = true

[functions.animals]
verify_jwt = true

[functions.admin-management]
verify_jwt = true

[functions.user-profile]
verify_jwt = false

[functions.admin-users]
verify_jwt = true
